import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Jhon',
      email: 'admin@cafe.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Sam',
      email: 'Sam@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: 0,
      slug: 'Cheese-Pizza',
      name: 'Cheese Pizza',
      category: 'Pizza',
      image: '/images/pizza1.jpg',
      price: 200,
      rating: 4.5,
      numReviews: 10,
      descriptionL: 'Authentic cheese pizza',
    },
    {
      id: 1,
      slug: 'Tandoori-Pizza',
      name: 'Tandoori Pizza',
      category: 'Pizza',
      image: '/images/pizza2.jpg',
      price: 180,
      rating: 4.6,
      numReviews: 20,
      descriptionL: 'Authentic Tandoori pizza',
    },
    {
      id: 2,
      slug: 'Veg-Pizza',
      name: 'Veg Pizza',
      category: 'Pizza',
      image: '/images/pizza3.jpg',
      price: 220,
      rating: 4.5,
      numReviews: 16,
      descriptionL: 'Authentic veg pizza',
    },
    {
      id: 3,
      slug: 'Chicken-Pizza',
      name: 'Chicken Pizza',
      category: 'Pizza',
      image: '/images/pizza4.jpg',
      price: 290,
      rating: 4.8,
      numReviews: 40,
      descriptionL: 'Authentic Chicken pizza',
    },
    {
      id: 4,
      slug: 'Classic-Pizza',
      name: 'Classic Pizza',
      category: 'Pizza',
      image: '/images/pizza5.jpg',
      price: 300,
      rating: 4.9,
      numReviews: 19,
      descriptionL: 'Authentic Classic pizza',
    },
    {
      id: 5,
      slug: 'Supreme-Pizza',
      name: 'Supreme Pizza',
      category: 'Pizza',
      image: '/images/pizza6.jpg',
      price: 200,
      rating: 4.5,
      numReviews: 10,
      descriptionL: 'Authentic cheese pizza',
    },
    {
      id: 6,
      slug: 'Barbeque-Pizza',
      name: 'Barbeque Pizza',
      category: 'Pizza',
      image: '/images/pizza6.jpg',
      price: 200,
      rating: 4.5,
      numReviews: 10,
      descriptionL: 'Authentic cheese pizza',
    },
  ],
};

export default data;
